### ISSUE TITLE
Keeps reloading the todoist block. 

### ISSUE THREAD

**Issue by siddhant-mohan** [alexfruehwirth/N1TodoistIntegration#7]
Hey,
it worked for one email and then it keeps relading the todoist block again and again. I checked the developer console and the error coming is 

todoist-task-store.es6 [sm]:265 Error: Too Many Requests
    at Request.callback (/Users/siddhant/.nylas-mail/packages/N1TodoistIntegration/node_modules/superagent/lib/node/index.js:698:17)
    at IncomingMessage.<anonymous> (/Users/siddhant/.nylas-mail/packages/N1TodoistIntegration/node_modules/superagent/lib/node/index.js:922:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Can you pls check this.

**Comment by alexfruehwirth** [comment]
Hey,
which OS are you one?
Are you using a special nylas theme?

Thanks!

**Comment by siddhant-mohan** [comment]
mac 10.12.4
nope. changed it to default. still getting the bug.
